### ISSUE TITLE
Attempting to connect crashes

### ISSUE THREAD

**Issue by Efreak** [wseemann/RoMote#2]
Phone: Romote crashed on first run. It ran fine at first in second run, however it only showed one of two Rokus; on trying to connect to the newer Roku manually (by IP address) it crashed.
Tablet: same as phone, but never saw any devices. 

New Roku: 3600X (stick)
Software version: 7.7.0 build 4135-24
Devices:
1. xt1528 running 5.1.1 stock VZW/Moto. No logcat available.
2. Nexus 7 (2013) wif running lineageos 14.1-20170912-NIGHTLY-flo (nougat/7.1.2). Partial logcats below (if you need more, please let me know.)

Old Roku: Roku 2 XS
Software version:?? (not in use)

### firewalled (afwall+), blocked on wan but not lan; detects no devices, crashes after entering ip manually:
```
--------- beginning of crash
09-23 13:19:03.662 E/AndroidRuntime(19481): FATAL EXCEPTION: main
09-23 13:19:03.662 E/AndroidRuntime(19481): Process: wseemann.media.romote, PID: 19481
09-23 13:19:03.662 E/AndroidRuntime(19481): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jdom2.Element.getValue()' on a null object reference
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at wseemann.media.romote.parser.DeviceInfoParser.parse(DeviceInfoParser.java:46)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at wseemann.media.romote.fragment.ManualConnectionFragment$2.onResponse(ManualConnectionFragment.java:96)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at wseemann.media.romote.fragment.ManualConnectionFragment$2.onResponse(ManualConnectionFragment.java:89)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:60)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at android.os.Handler.handleCallback(Handler.java:751)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at android.os.Looper.loop(Looper.java:154)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at java.lang.reflect.Method.invoke(Native Method)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-23 13:19:03.662 E/AndroidRuntime(19481): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-23 13:19:03.722 W/ActivityManager(565):   Force finishing activity wseemann.media.romote/.activity.ManualConnectionActivity
09-23 13:19:03.754 W/DropBoxManagerService(565): Dropping: data_app_crash (1288 > 0 bytes)
09-23 13:19:03.943 I/OpenGLRenderer(565): Initialized EGL, version 1.4
```

### firewall disabled, crashes on start:
```
09-23 13:36:03.778 I/ActivityManager(565): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=wseemann.media.romote/.activity.MainActivity (has extras)} from uid 10074 on display 0
09-23 13:36:03.969 I/ActivityManager(565): Start proc 25351:wseemann.media.romote/u0a296 for activity wseemann.media.romote/.activity.MainActivity
09-23 13:36:03.995 I/PBSessionCacheImpl(16151): Deleted sessionId[71034355379525814] from persistence.
09-23 13:36:04.126 W/System  (25351): ClassLoader referenced unknown path: /data/app/wseemann.media.romote-1/lib/arm
09-23 13:36:04.300 W/art     (25351): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-23 13:36:04.474 I/ActivityManager(565): START u0 {cmp=wseemann.media.romote/.activity.ConfigureDeviceActivity} from uid 10296 on display 0
09-23 13:36:04.896 I/Adreno-EGL(25351): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-23 13:36:04.900 W/RenderThread(25371): type=1400 audit(0.0:1871): avc: denied { read } for name="gpuclk" dev="sysfs" ino=10104 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-23 13:36:04.903 D/OpenGLRenderer(25351): Swap behavior 1
09-23 13:36:04.909 W/Adreno-ES20(25351): <get_gpu_clk:229>: open failed: errno 13
09-23 13:36:05.248 I/ActivityManager(565): Displayed wseemann.media.romote/.activity.ConfigureDeviceActivity: +705ms (total +1s345ms)
09-23 13:36:06.368 I/art     (1384): Background partial concurrent mark sweep GC freed 300844(12MB) AllocSpace objects, 0(0B) LOS objects, 40% free, 19MB/33MB, paused 549us total 130.920ms
09-23 13:36:09.348 W/System  (25351): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
09-23 13:36:09.368 D/NetworkSecurityConfig(25351): No Network Security Config specified, using platform default
09-23 13:36:09.511 E/AndroidRuntime(25351): FATAL EXCEPTION: ModernAsyncTask #1
09-23 13:36:09.511 E/AndroidRuntime(25351): Process: wseemann.media.romote, PID: 25351
09-23 13:36:09.511 E/AndroidRuntime(25351): java.lang.RuntimeException: An error occurred while executing doInBackground()
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.lang.Thread.run(Thread.java:761)
09-23 13:36:09.511 E/AndroidRuntime(25351): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jdom2.Element.getValue()' on a null object reference
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at wseemann.media.romote.parser.DeviceInfoParser.parse(DeviceInfoParser.java:46)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at wseemann.media.romote.loader.AvailableDevicesLoader.loadInBackground(AvailableDevicesLoader.java:52)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at wseemann.media.romote.loader.AvailableDevicesLoader.loadInBackground(AvailableDevicesLoader.java:23)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-23 13:36:09.511 E/AndroidRuntime(25351): 	... 3 more
09-23 13:36:09.529 W/ActivityManager(565):   Force finishing activity wseemann.media.romote/.activity.ConfigureDeviceActivity
09-23 13:36:09.555 W/DropBoxManagerService(565): Dropping: data_app_crash (1625 > 0 bytes)
09-23 13:36:09.702 I/OpenGLRenderer(565): Initialized EGL, version 1.4
09-23 13:36:09.702 D/OpenGLRenderer(565): Swap behavior 1
09-23 13:36:10.014 I/art     (565): Background partial concurrent mark sweep GC freed 15642(839KB) AllocSpace objects, 4(80KB) LOS objects, 33% free, 25MB/38MB, paused 4.302ms total 411.041ms
09-23 13:36:10.187 I/ActivityManager(565): Killing 20206:com.android.providers.calendar/u0a5 (adj 906): empty #17
09-23 13:36:10.212 D/ActivityManager(565): cleanUpApplicationRecord -- 20206
09-23 13:36:11.340 I/onOrientationChange(13612): old: Portrait new: Landscape
09-23 13:36:11.341 I/OverlayButton(13612): right handed, old: Portrait new: Landscape
09-23 13:36:11.474 I/onOrientationChange(13612): old: Portrait new: Unknown
09-23 13:36:11.499 W/AppOps  (565): Finishing op nesting under-run: uid 10494 pkg com.gabm.tapandturn code 24 time=0 duration=0 nesting=0
09-23 13:36:11.539 I/onOrientationChange(13612): old: Portrait new: Portrait
09-23 13:36:13.289 I/onOrientationChange(13612): old: Portrait new: Unknown
09-23 13:36:13.420 I/onOrientationChange(13612): old: Portrait new: Portrait
09-23 13:36:14.045 I/EventLogSendingHelper(16151): Sending log events.
09-23 13:36:15.087 I/ActivityManager(565): Killing 25351:wseemann.media.romote/u0a296 (adj 900): crash
09-23 13:36:15.087 D/ActivityManager(565): cleanUpApplicationRecord -- 25351
09-23 13:36:15.096 I/ActivityManager(565): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=wseemann.media.romote/.activity.MainActivity bnds=[713,992][940,1188] (has extras)} from uid 10296 on display 0
09-23 13:36:15.138 W/ActivityManager(565): Unable to start service Intent { cmp=com.teslacoilsw.notifier/.NotificationService (has extras) } U=0: not found
09-23 13:36:15.156 E/ActivityManager(565): applyOptionsLocked: Unknown animationType=0
09-23 13:36:15.161 W/SearchServiceClient(16151): Starting with NO_SESSION handoverId is deprecated. Just don't. You will break.
09-23 13:36:15.166 D/GraphicsStats(565): Buffer count: 12
09-23 13:36:15.211 I/ActivityManager(565): Start proc 25415:wseemann.media.romote/u0a296 for activity wseemann.media.romote/.activity.MainActivity
09-23 13:36:15.261 E/PBSessionCacheImpl(16151): sessionId[71034355379525814] not persisted.
09-23 13:36:15.284 I/PBSessionCacheImpl(16151): Deleted sessionId[71034355379525814] from persistence.
09-23 13:36:15.297 W/Settings(16151): Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-23 13:36:15.317 W/Settings(16151): Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-23 13:36:15.328 W/AppOps  (565): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-23 13:36:15.342 W/art     (16151): Long monitor contention with owner main (16151) at void com.google.android.apps.gsa.search.core.service.SearchService.a(com.google.android.apps.gsa.search.core.service.d, boolean)(SourceFile:289) waiters=0 in void com.google.android.apps.gsa.search.core.service.d.b(long, boolean) for 118ms
09-23 13:36:15.349 I/MicroDetectionState(16151): Keep running hotword in interactor process
09-23 13:36:15.359 I/PBSessionCacheImpl(16151): Deleted sessionId[71034355379525814] from persistence.
09-23 13:36:15.386 W/System  (25415): ClassLoader referenced unknown path: /data/app/wseemann.media.romote-1/lib/arm
09-23 13:36:15.457 W/art     (25415): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-23 13:36:15.596 I/ActivityManager(565): START u0 {cmp=wseemann.media.romote/.activity.ConfigureDeviceActivity} from uid 10296 on display 0
09-23 13:36:15.969 I/Adreno-EGL(25415): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-23 13:36:15.980 W/RenderThread(25433): type=1400 audit(0.0:1872): avc: denied { read } for name="gpuclk" dev="sysfs" ino=10104 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-23 13:36:15.978 I/OpenGLRenderer(25415): Initialized EGL, version 1.4
09-23 13:36:15.979 D/OpenGLRenderer(25415): Swap behavior 1
09-23 13:36:15.986 W/Adreno-ES20(25415): <get_gpu_clk:229>: open failed: errno 13
09-23 13:36:16.016 E/LocSvc_eng(565): W/int loc_eng_inject_location(loc_eng_data_s_type &, double, double, float): log_eng state error: instance not initialized
09-23 13:36:16.056 E/AlarmManagerService(565): Unable to set alarm to 1506267000.000000000: Invalid argument
09-23 13:36:16.068 I/GeofencerStateMachine(1406): {removed}
09-23 13:36:16.071 I/LocationFilter(1406): Stable location not established yet. Returning original location.
09-23 13:36:16.081 I/Places  (1406): Converted 7 out of 8 WiFi scans
09-23 13:36:16.166 W/ctxmgr  (1406): {removed}
09-23 13:36:16.193 E/AlarmManagerService(565): Unable to set alarm to 1506267000.000000000: Invalid argument
09-23 13:36:16.203 I/ActivityManager(565): Displayed wseemann.media.romote/.activity.ConfigureDeviceActivity: +536ms (total +1s46ms)
09-23 13:36:16.211 I/GeofencerStateMachine(1406): sendNewLocationAvailability: availability=LocationAvailability[isLocationAvailable: true]
09-23 13:36:16.293 I/GCoreUlr(1406): Successfully inserted 1 locations
09-23 13:36:17.242 D/LuxLevels(565): bright hysteresis constant= 0.1, threshold=27.235752, lux=24.759773
09-23 13:36:17.242 D/LuxLevels(565): dark hysteresis constant= 0.2, threshold=19.80782, lux=24.759773
09-23 13:36:19.558 W/System  (25415): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
09-23 13:36:19.569 D/NetworkSecurityConfig(25415): No Network Security Config specified, using platform default
09-23 13:36:19.848 E/AndroidRuntime(25415): FATAL EXCEPTION: ModernAsyncTask #1
09-23 13:36:19.848 E/AndroidRuntime(25415): Process: wseemann.media.romote, PID: 25415
09-23 13:36:19.848 E/AndroidRuntime(25415): java.lang.RuntimeException: An error occurred while executing doInBackground()
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.lang.Thread.run(Thread.java:761)
09-23 13:36:19.848 E/AndroidRuntime(25415): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jdom2.Element.getValue()' on a null object reference
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at wseemann.media.romote.parser.DeviceInfoParser.parse(DeviceInfoParser.java:46)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at wseemann.media.romote.loader.AvailableDevicesLoader.loadInBackground(AvailableDevicesLoader.java:52)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at wseemann.media.romote.loader.AvailableDevicesLoader.loadInBackground(AvailableDevicesLoader.java:23)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-23 13:36:19.848 E/AndroidRuntime(25415): 	... 3 more
09-23 13:36:19.860 W/ActivityManager(565):   Force finishing activity wseemann.media.romote/.activity.ConfigureDeviceActivity
09-23 13:36:19.884 W/DropBoxManagerService(565): Dropping: data_app_crash (1625 > 0 bytes)
09-23 13:36:20.030 I/OpenGLRenderer(565): Initialized EGL, version 1.4
09-23 13:36:20.030 D/OpenGLRenderer(565): Swap behavior 1
09-23 13:36:20.327 I/art     (565): Background partial concurrent mark sweep GC freed 36957(1952KB) AllocSpace objects, 4(76KB) LOS objects, 33% free, 25MB/38MB, paused 4.180ms total 398.254ms
09-23 13:36:23.178 I/ActivityManager(565): Killing 25415:wseemann.media.romote/u0a296 (adj 900): crash
09-23 13:36:23.191 D/ActivityManager(565): cleanUpApplicationRecord -- 25415
09-23 13:36:23.208 W/InputEventReceiver(565): Attempted to finish an input event but the input event receiver has already been disposed.
09-23 13:36:23.211 W/ActivityManager(565): Unable to start service Intent { cmp=com.teslacoilsw.notifier/.NotificationService (has extras) } U=0: not found
09-23 13:36:23.216 W/SearchServiceClient(16151): Starting with NO_SESSION handoverId is deprecated. Just don't. You will break.
09-23 13:36:23.252 E/PBSessionCacheImpl(16151): sessionId[71034355379525814] not persisted.
09-23 13:36:23.281 I/PBSessionCacheImpl(16151): Deleted sessionId[71034355379525814] from persistence.
09-23 13:36:23.284 W/Settings(16151): Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-23 13:36:23.294 W/Settings(16151): Setting mobile_data has moved from android.provider.Settings.Secure to android.provider.Settings.Global.
09-23 13:36:23.296 D/GraphicsStats(565): Buffer count: 12
09-23 13:36:23.333 I/MicroDetectionState(16151): Keep running hotword in interactor process
09-23 13:36:23.402 W/AppOps  (565): Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
09-23 13:36:24.865 I/ActivityManager(565): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=wseemann.media.romote/.activity.MainActivity (has extras)} from uid 10074 on display 0
09-23 13:36:25.021 I/ActivityManager(565): Start proc 25474:wseemann.media.romote/u0a296 for activity wseemann.media.romote/.activity.MainActivity
09-23 13:36:25.043 I/PBSessionCacheImpl(16151): Deleted sessionId[71034355379525814] from persistence.
09-23 13:36:25.093 D/LuxLevels(565): bright hysteresis constant= 0.1, threshold=30.453487, lux=27.684988
09-23 13:36:25.093 D/LuxLevels(565): dark hysteresis constant= 0.2, threshold=22.147991, lux=27.684988
09-23 13:36:25.116 W/System  (25474): ClassLoader referenced unknown path: /data/app/wseemann.media.romote-1/lib/arm
09-23 13:36:25.202 W/art     (25474): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-23 13:36:25.308 I/ActivityManager(565): START u0 {cmp=wseemann.media.romote/.activity.ConfigureDeviceActivity} from uid 10296 on display 0
09-23 13:36:25.672 I/Adreno-EGL(25474): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
09-23 13:36:25.682 I/OpenGLRenderer(25474): Initialized EGL, version 1.4
09-23 13:36:25.682 D/OpenGLRenderer(25474): Swap behavior 1
09-23 13:36:25.680 W/RenderThread(25494): type=1400 audit(0.0:1873): avc: denied { read } for name="gpuclk" dev="sysfs" ino=10104 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
09-23 13:36:25.688 W/Adreno-ES20(25474): <get_gpu_clk:229>: open failed: errno 13
09-23 13:36:25.936 I/ActivityManager(565): Displayed wseemann.media.romote/.activity.ConfigureDeviceActivity: +556ms (total +960ms)
09-23 13:36:28.173 W/System  (25474): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
09-23 13:36:28.184 D/NetworkSecurityConfig(25474): No Network Security Config specified, using platform default
09-23 13:36:28.415 E/AndroidRuntime(25474): FATAL EXCEPTION: ModernAsyncTask #1
09-23 13:36:28.415 E/AndroidRuntime(25474): Process: wseemann.media.romote, PID: 25474
09-23 13:36:28.415 E/AndroidRuntime(25474): java.lang.RuntimeException: An error occurred while executing doInBackground()
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.lang.Thread.run(Thread.java:761)
09-23 13:36:28.415 E/AndroidRuntime(25474): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jdom2.Element.getValue()' on a null object reference
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at wseemann.media.romote.parser.DeviceInfoParser.parse(DeviceInfoParser.java:46)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at wseemann.media.romote.loader.AvailableDevicesLoader.loadInBackground(AvailableDevicesLoader.java:52)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at wseemann.media.romote.loader.AvailableDevicesLoader.loadInBackground(AvailableDevicesLoader.java:23)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-23 13:36:28.415 E/AndroidRuntime(25474): 	... 3 more
09-23 13:36:28.419 W/ActivityManager(565):   Force finishing activity wseemann.media.romote/.activity.ConfigureDeviceActivity
09-23 13:36:28.450 W/DropBoxManagerService(565): Dropping: data_app_crash (1625 > 0 bytes)
09-23 13:36:28.621 I/OpenGLRenderer(565): Initialized EGL, version 1.4
09-23 13:36:28.621 D/OpenGLRenderer(565): Swap behavior 1
09-23 13:36:28.853 I/art     (565): Background partial concurrent mark sweep GC freed 20041(1093KB) AllocSpace objects, 3(60KB) LOS objects, 33% free, 25MB/38MB, paused 4.394ms total 371.765ms
09-23 13:36:29.750 I/ActivityManager(565): Killing 25474:wseemann.media.romote/u0a296 (adj 900): crash
09-23 13:36:29.750 D/ActivityManager(565): cleanUpApplicationRecord -- 25474
```

**Comment by Efreak** [comment]
Fixed! Thanks!
